### ISSUE TITLE
Assets not exists after installing and configure

### ISSUE THREAD

**Issue by Meklad** [arabnewscms/it#3]
After install and configure, and when i visit admin panel or "IT TOOLS" there is many errors happened because there is the browser can't find assets like bootstrap, jquery, login.rtl ... etc.

how can i find all this assets because there is a lot of files is not there.

**Comment by arabnewscms** [comment]
please call this command in your terminal 
`php artisan vendor:publish --force  --provider="Phpanonymous\It\ItApplication"
`

to get more information about this package please visit this website 
https://it.phpanonymous.com/docs/1.0/Installation/Install_(it)
