### ISSUE TITLE
grammar mistake

### ISSUE THREAD

**Issue by nourdar** [arabnewscms/it#5]
hello ,
while i'm doing it:generate it asked me this question  
you want me a create database in your engine or you are already created database with name laravel-vue?  (yes/no)
i think this form is wrong the right sentence is 
do you want me to create a database in your engine or you have already created database with name "xxxxxx" ?  (yes/no)

**Comment by arabnewscms** [comment]
okay bro we will fix that in new comes version 1.4
thanks for your help
