### ISSUE TITLE
Admin login and register forms not working on server

### ISSUE THREAD

**Issue by Nesma-Hamdy** [arabnewscms/it#7]
I have installed It package locally and it is working fine but after uploading the files to the host login and register forms didn't work it keeps resulting the error
419 Page Expired
I have changed the permissions for storage and bootstrap cache but with no luck
and the language links always redirects me to the default language (ar) it didn't work either.
is there any configs missing ? I have set the APP_URL and ASSET_URL in the .env file

**Comment by arabnewscms** [comment]
in public/index.php add this on first line 
`<?php
ob_start();
session_start();

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));
` ...
your host maybe not initialize  session driver  
go to storage/session delete all files on this folder and test your application again 
tell me if you facing same error again

**Comment by arabnewscms** [comment]
laravel session not persisting 
in public/index.php add this on first line 
ob_start();
session_start();

```
<?php
ob_start();
session_start();

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));
```

...
your host maybe not initialize  session driver  
go to storage/session delete all files on this folder and test your application again 
tell me if you facing same error again

**Comment by Nesma-Hamdy** [comment]
It's working now, thanks a lot

**Comment by arabnewscms** [comment]
good job 
have a nice day
